config/routes.rb
Rails.application.routes.draw do

  resources :time_tracks

  resources :users do
    member do
      get :add_entry
    end
  end

  get 'logs/login'

  root 'users#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_track.rb
class TimeTrack < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :time_tracks
  validates :name, presence: true
  validates :email, presence: true
  validates :age, presence:true
  validates :phone, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController  
  def login
    render html: "no elo kuwa"
  end
end

app/controllers/time_tracks_controller.rb
class TimeTracksController < ApplicationController
  before_action :set_time_track, only: [:show, :edit, :update, :destroy, :addEntry]

  # GET /time_tracks
  # GET /time_tracks.json
  def index
    @time_tracks = TimeTrack.all
  end

  # GET /time_tracks/1
  # GET /time_tracks/1.json
  def show
  end

  # GET /time_tracks/new
  def new
    @time_track = TimeTrack.new
  end

  # GET /time_tracks/1/edit
  def edit
  end

  # POST /time_tracks
  # POST /time_tracks.json
  def create
    @time_track = TimeTrack.new(time_track_params)

    respond_to do |format|
      if @time_track.save
        format.html { redirect_to @time_track, notice: 'Time track was successfully created.' }
        format.json { render :show, status: :created, location: @time_track }
      else
        format.html { render :new }
        format.json { render json: @time_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_tracks/1
  # PATCH/PUT /time_tracks/1.json
  def update
    respond_to do |format|
      if @time_track.update(time_track_params)
        format.html { redirect_to @time_track, notice: 'Time track was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_track }
      else
        format.html { render :edit }
        format.json { render json: @time_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_tracks/1
  # DELETE /time_tracks/1.json
  def destroy
    @time_track.destroy
    respond_to do |format|
      format.html { redirect_to time_tracks_url, notice: 'Time track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_track
      @time_track = TimeTrack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_track_params
      params.require(:time_track).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include TimeTracksHelper

  before_action :set_user, only: [:show, :edit, :update, :destroy, :add_entry]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def add_entry
    timetrack = @user.time_tracks.order(created_at: :desc).first
    if timetrack.present? && timetrack.entry_time_end.nil?
      timesummary=(Time.now - timetrack.entry_time_start)

      if timesummary > 60
      timetrack.update_attributes(entry_time_end: Time.now, entry_time_summary: timesummary)
       flash[:notice] = 'Pa pa '+@user.name+', Zakończyłeś pracę o ' + Time.now.strftime('%H:%M:%S').to_s + ' pracowałeś przez ' + format_time_summary(timesummary)
     end
    else
      @user.time_tracks.create(entry_time_start: Time.now)
      flash[:notice] =  'Cześć '+@user.name+', Rozpocząłeś pracę o ' + Time.now.strftime('%H:%M:%S').to_s
    end
redirect_to @user
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @timetracks = @user.time_tracks
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :age, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/time_tracks_helper.rb
module TimeTracksHelper
  def format_time_summary(entry_time_summary)
    hours = (entry_time_summary / 3600)
    minutes = ((entry_time_summary % 3600) / 60)
    seconds = (((entry_time_summary % 3600) % 60))

    return number_with_precision(hours,precision: 0 ).to_s.rjust(2,'0') + ":" + number_with_precision(minutes,precision: 0 ).to_s.rjust(2,'0') + ":" + number_with_precision(seconds,precision: 0 ).to_s.rjust(2,'0')
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logs/login.html.erb
<h2>naming controller "logs" wasn't such a good idea</h2>

app/views/time_tracks/_form.html.erb
<%= form_with(model: time_track, local: true) do |form| %>
  <% if time_track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_track.errors.count, "error") %> prohibited this time_track from being saved:</h2>

      <ul>
      <% time_track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :time_track_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :time_track_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/time_tracks/edit.html.erb
<h1>Editing Time Track</h1>

<%= render 'form', time_track: @time_track %>

<%= link_to 'Show', @time_track %> |
<%= link_to 'Back', time_tracks_path %>

app/views/time_tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Time Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_tracks.each do |time_track| %>
      <tr>
        <td><%= time_track.content %></td>
        <td><%= time_track.user_id %></td>
        <td><%= link_to 'Show', time_track %></td>
        <td><%= link_to 'Edit', edit_time_track_path(time_track) %></td>
        <td><%= link_to 'Destroy', time_track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time Track', new_time_track_path %>

app/views/time_tracks/new.html.erb
<h1>New Time Track</h1>

<%= render 'form', time_track: @time_track %>

<%= link_to 'Back', time_tracks_path %>

app/views/time_tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @time_track.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @time_track.user_id %>
</p>

<%= link_to 'Edit', edit_time_track_path(@time_track) %> |
<%= link_to 'Back', time_tracks_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age, id: :user_age %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :user_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/add_entry.html.erb
<h2>siema</h2>
<p>
  
</p>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.age %></td>
        <td><%= user.phone %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.haml
%h1#notice= notice
- if @timetracks.count >0
  %br/
  %br/
  %br/
  %br/
  %h2 Lista wejść:
- @timetracks.each do |timetrack|
  %p
    W dniu
    %strong
      = timetrack.entry_time_start.strftime('%d-%m-%Y')
    = "od  #{timetrack.entry_time_start.strftime('%H:%M:%S')}"
    - unless timetrack.entry_time_end.nil?
      = "do #{timetrack.entry_time_end.strftime('%H:%M:%S')}"
      = "pracowałeś przez: #{format_time_summary(timetrack.entry_time_summary)}"